### PR TITLE
Contact-page-added

### PR DESCRIPTION
**Pull request by sameersrivastava13**
Please review the code and let me know if i have to make any changes.
@anushbhatia @smaranjitghose 

auto_vaidya

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@sameersrivastava13 Can you please commit to the master branch. Once we have finalized the UI for the frontend, we would prefer to integrate it in the backend at once.

Nice work with the contact page!

@anushbhatia might provide some more enhancement suggestions

**Comment by anushbhatia** [comment]
use default text field materialize css and push this in front end no need to use backend service as of now use any [Formspree](https://formspree.io/) this for integration and if possible add validations through js in it and as soon as the message is sent use a toast for the notification part. Push into the front end branch as of now avoid using backend for just a form.

**Comment by sameersrivastava13** [comment]
1.  @anushbhatia or i can use the flask extensions to create forms and add validations that will be much better i believe.
2.  Also i have already used the flasks built in message flashing system which is flashing a success message as soon as the message has been sent.

[https://flask-wtf.readthedocs.io/en/stable/](url)

**Comment by anushbhatia** [comment]
1. you can use built in validation for that
2.I know i have gone through it but the UI of that looks pretty ugly who would like see their notification in the top of the browser. Just parse that message in the toast provided by materialize css.
3. We don't want their data as of now. We just want is the their email id for further communication via this and what will we do by integrating a backend just for the sake of a form that's not a valid reason to have a system for that. If we were an active startup competing with lots of forms dail that would be a great solution but for current scenario its highly irrelevant.

For any further doubts feel free to contact me

**Comment by sameersrivastava13** [comment]
If only the front end is to be added for the contact page.
I have done the form validation using javascript.
Please see this if it is okay.
@anushbhatia @smaranjitghose 

Screenshot (31)

**Comment by smaranjitghose** [comment]
> @sameersrivastava13 Can you please commit to the master branch. Once we have finalized the UI for the frontend, we would prefer to integrate it in the backend at once.
> 
> Nice work with the contact page!
> 
> @anushbhatia might provide some more enhancement suggestions

@sameersrivastava13 Can you please push this to the master branch, we are maintaining it exclusively for frontend without the flask backend

**Comment by smaranjitghose** [comment]
Additionally, please ensure that the color scheme is consistent throughout the website for all the pages

**Pull request closed without merging**
