### PR TITLE
Added the streamlit app

### PR DESCRIPTION
**Pull request by Preetesh21**
This PR is for issue #5 
Added streamlit version for the diabetes prediction.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@Preetesh21 
It is preferred, we keep the barebones of the streamlit web app inside the app.py. For the prediction function used in each of the pages(or use cases) define it in a separate script and import in app.py. Add the app.py should be at the root level and not inside any other folder so that there are no hiccups when we host our web app. Have a look at my img_ai_boilerplate repo for reference

**Comment by Preetesh21** [comment]
Sir,so basically I need to define the predict function inside another script in the diabetes folder and call it in the app.py (present at the root level) which is the streamlit app containing the form for inputs.Am I getting it right?

**Comment by smaranjitghose** [comment]
@Preetesh21 I have updated the ReadME with detailed guidelines for PR. Please have a look

**Comment by Preetesh21** [comment]
Yes sir.
Sir, So now I have to make the app.py at the root level which takes scripts from different projects?
and the app.py shall have options for all the projects right?

**Comment by smaranjitghose** [comment]
> Yes sir.
> Sir, So now I have to make the app.py at the root level which takes scripts from different projects?
> and the app.py shall have options for all the projects right?

Yes

**Comment by smaranjitghose** [comment]
> > Yes sir.
> > Sir, So now I have to make the app.py at the root level which takes scripts from different projects?
> > and the app.py shall have options for all the projects right?
> 
> Yes

Can you please continue this in a new PR and have a look at the issues as well.

**Comment by Preetesh21** [comment]
Sure sir.

**Pull request closed without merging**
