### PR TITLE
Added Model for detecting Skin Cancer

### PR DESCRIPTION
**Pull request by SoniGarima**
Hello Sir,
I have trained a deep learning model ( mobile-net ) to detect the type of Skin Cancer ( having 7 classes ). 
Data-set used is skin-cancer-mnist-ham10000. 
The link to colab is - [link](https://colab.research.google.com/drive/1kyYvCBJIt5AAn_u9Oy1-LZ21kkUqEK94?usp=sharing). 
The saved model is present in saved_models directory.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> Hello Sir,
> I have trained a deep learning model ( mobile-net ) to detect the type of Skin Cancer ( having 7 classes ).
> Data-set used is skin-cancer-mnist-ham10000.
> The link to colab is - [link](https://colab.research.google.com/drive/1kyYvCBJIt5AAn_u9Oy1-LZ21kkUqEK94?usp=sharing).
> The saved model is present in saved_models directory.

Can you please grant me access to the colab notebook

**Comment by smaranjitghose** [comment]
@SoniGarima can you please have a look at the ReadMe for the PR guidelines

**Comment by SoniGarima** [comment]
> Can you please grant me access to the colab notebook

I have granted you the access.

**Comment by SoniGarima** [comment]
> @SoniGarima can you please have a look at the ReadMe for the PR guidelines

Should I make the required changes and give the PR again?

**Comment by smaranjitghose** [comment]
> > @SoniGarima can you please have a look at the ReadMe for the PR guidelines
> 
> Should I make the required changes and give the PR again?

Yes please

**Comment by SoniGarima** [comment]
> Yes please

Sure sir.

**Pull request closed without merging**
