### PR TITLE
Logo Sample Added

### PR DESCRIPTION
**Pull request by ritiksoni00**

### CODE REVIEW

**Review by abhu-A-J — APPROVED** [review]
@ritiksoni00 These look good to me! I'm approving this for merge!

**Review by anushbhatia — CHANGES_REQUESTED** [review]
something related to medical

**Comment by ritiksoni00** [comment]
image
@abhu-A-J  @anushbhatia  please check this??

**Comment by smaranjitghose** [comment]
> image
> @abhu-A-J @anushbhatia please check this??

Looks good to me. I guess @anushbhatia might have feedback for the font

**Comment by anushbhatia** [comment]
the logo is already merged @smaranjitghose

**Comment by ritiksoni00** [comment]
> the logo is already merged @smaranjitghose

This logo has already merged??

**Comment by anushbhatia** [comment]
see @sameersrivastava13 had made a better logo but in the issue, I have suggested a logo if you can make something minimal like that then it would be great

**Comment by ritiksoni00** [comment]
ill try one more time if that looks good to you then merge it! simple :)

**Comment by ritiksoni00** [comment]
let's close this!

**Pull request closed without merging**
