### PR TITLE
added parallax effect 

### PR DESCRIPTION
**Pull request by AshutoshDash1999**
revamped the landing page by adding parallax effect in project and contact section.

Screencast from 17-08-20 11 55 53 AM IST

### CODE REVIEW

**Comment by anushbhatia** [comment]
Add dark layer of opacity on the parallax and these look really weird. For Different Pages use parallax effect. Each disease  page

**Comment by AshutoshDash1999** [comment]
@anushbhatia are you sure you wanna add a black tint because the texts are also black and I don't think it will hold up a good contrast.

**Comment by anushbhatia** [comment]
change the text to white then everywhere. Using the same template try creating a disease page https://www.townscript.com/in/vadodara for ideas

**Comment by AshutoshDash1999** [comment]
@anushbhatia how's it? I changed the text to white and added a black tint to the parallax image
Screencast from 18-08-20 07 43 53 PM IST

**Comment by AshutoshDash1999** [comment]
> change the text to white then everywhere. Using the same template try creating a disease page https://www.townscript.com/in/vadodara for ideas

so shall i make a disease template page which includes parallax or same as the link which you provided?

**Comment by anushbhatia** [comment]
> > change the text to white then everywhere. Using the same template try creating a disease page https://www.townscript.com/in/vadodara for ideas
> 
> so shall i make a disease template page which includes parallax or same as the link which you provided?

yes

**Comment by AshutoshDash1999** [comment]
please check the latest PR on parallax effect in home page

**Pull request closed without merging**
