### PR TITLE
Create Feature.request.md

### PR DESCRIPTION
**Pull request by ritiksoni00**
any suggestion will be appreciable!!

### CODE REVIEW

**Comment by anushbhatia** [comment]
@smaranjitghose

**Comment by ritiksoni00** [comment]
is it not CH20 Code

**Comment by ritiksoni00** [comment]
@smaranjitghose  please tell if it wasnt??

**Comment by ritiksoni00** [comment]
> @smaranjitghose please tell if it wasnt??
@abhu-A-J  @smaranjitghose  ??

**Comment by smaranjitghose** [comment]
> > @smaranjitghose please tell if it wasn't??
> > @abhu-A-J  @smaranjitghose  @anushbhatia  ?? please assign it and label it too   please :0

Done

**Pull request merged**
