### PR TITLE
Update the style to make the banner image responsive

### PR DESCRIPTION
**Pull request by ymaheshwari1**
Made the banner image responsive and also updated the card responsiveness on the mobile devices.

localhost_5500_(Pixel 2 XL)

Issue #24

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Great work indeed just some minor changes I want to request to this layout.
https___deploy-preview-39--autovaidya netlify app and 15 more pages - Personal - Microsoft​ Edge 01-09-2020 00_21_25

**Comment by ymaheshwari1** [comment]
@anushbhatia Can you suggest some changes to the layout?

**Comment by ymaheshwari1** [comment]
@anushbhatia Please send me the PR/issue link of the finalized logo

**Comment by anushbhatia** [comment]
@sameersrivastava13 will give you the logo

**Comment by ymaheshwari1** [comment]
@anushbhatia Should I remove the name in the mobile version and only keep the logo?

**Comment by ymaheshwari1** [comment]
@smaranjitghose Why this pr is closed?

**Pull request closed without merging**
