### PR TITLE
Pr and issue template created!

### PR DESCRIPTION
**Pull request by ritiksoni00**
If i made a mistake Then Sorry for that! hope for the Best Journey GG

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> If i made a mistake Then Sorry for that! hope for the Best Journey GG

@ritiksoni00 These do not count for an effective contribution towards the program

**Comment by ritiksoni00** [comment]
What do you want In THese File? @smaranjitghose

**Comment by ritiksoni00** [comment]
@abhu-A-J  please look at this

**Comment by abhu-A-J** [comment]
@smaranjitghose Are templated not accepted as PR's?? 
We can still merge them and not give points?? Will be helpful for the project anyway?? Can you let me know please!

**Comment by ritiksoni00** [comment]
@smaranjitghose Please don't let this Work Being Garbage! I think it will Helpful for Project @abhu-A-J ??

**Pull request closed without merging**
